package ch.epfl.biop.operetta;

import loci.formats.FormatException;
import loci.formats.IFormatReader;
import loci.formats.meta.IMetadata;
import ome.units.quantity.Length;
import ome.xml.meta.OMEXMLMetadataRoot;
import ome.xml.model.Plate;
import ome.xml.model.Well;
import ome.xml.model.WellSample;

import java.io.IOException;
import java.util.List;

/**
 * Test to verify that a companion file generated from an archive
 * can be opened by Bio-Formats and used with OperettaManager.
 */
public class TestCompanionWithOperettaManager {

    public static void main(String... args) throws Exception {
        // Path to the companion file generated by CompanionFromArchiveGenerator
        String companionPath = "N:\\public\\linda.wedemann_GR-SCHUHMACHER\\ArchiveIssue\\Harmony-Archive\\IMAGES\\b60a54b4-c5de-4eb2-bcdd-12d4980b3973\\b60a54b4-c5de-4eb2-bcdd-12d4980b3973.companion.ome.lazy";//"F:/archive/YourPlateName.companion.ome";

        // Step 1: Try to open the companion file with Bio-Formats
        System.out.println("=== Step 1: Opening companion file with Bio-Formats ===");
        //IFormatReader reader;
        IFormatReader reader;
        try {
            reader = OperettaManager.Builder.createReader(companionPath);
            System.out.println("SUCCESS: Reader created");
        } catch (IOException | FormatException e) {
            System.err.println("FAILED: Could not create reader");
            e.printStackTrace();
            return;
        }

        // Step 2: Check basic reader info
        System.out.println("\n=== Step 2: Basic reader info ===");
        System.out.println("Format: " + reader.getFormat());
        System.out.println("Series count: " + reader.getSeriesCount());
        System.out.println("Current file: " + reader.getCurrentFile());

        // Step 3: Check metadata structure
        System.out.println("\n=== Step 3: Metadata structure ===");
        IMetadata metadata = (IMetadata) reader.getMetadataStore();

        // Check plate info
        int plateCount = metadata.getPlateCount();
        System.out.println("Plate count: " + plateCount);

        if (plateCount > 0) {
            String plateName = metadata.getPlateName(0);
            int plateRows = metadata.getPlateRows(0).getValue();
            int plateCols = metadata.getPlateColumns(0).getValue();
            System.out.println("Plate name: " + plateName);
            System.out.println("Plate dimensions: " + plateRows + " rows x " + plateCols + " cols");

            // Check well count
            int wellCount = metadata.getWellCount(0);
            System.out.println("Well count: " + wellCount);

            if (wellCount > 0) {
                // Check first well
                int wellRow = metadata.getWellRow(0, 0).getValue();
                int wellCol = metadata.getWellColumn(0, 0).getValue();
                System.out.println("First well: R" + (wellRow+1) + "-C" + (wellCol+1));

                // Check well samples (fields)
                int wellSampleCount = metadata.getWellSampleCount(0, 0);
                System.out.println("Fields per well: " + wellSampleCount);

                if (wellSampleCount > 0) {
                    // Check first field position
                    Length posX = metadata.getWellSamplePositionX(0, 0, 0);
                    Length posY = metadata.getWellSamplePositionY(0, 0, 0);
                    System.out.println("First field position: X=" + posX + ", Y=" + posY);
                }
            }
        }

        // Step 4: Check image/pixels info
        System.out.println("\n=== Step 4: Image dimensions ===");
        int imageCount = metadata.getImageCount();
        System.out.println("Image count: " + imageCount);

        if (imageCount > 0) {
            int sizeX = metadata.getPixelsSizeX(0).getValue();
            int sizeY = metadata.getPixelsSizeY(0).getValue();
            int sizeZ = metadata.getPixelsSizeZ(0).getValue();
            int sizeC = metadata.getPixelsSizeC(0).getValue();
            int sizeT = metadata.getPixelsSizeT(0).getValue();
            System.out.println("First image dimensions: X=" + sizeX + ", Y=" + sizeY +
                    ", Z=" + sizeZ + ", C=" + sizeC + ", T=" + sizeT);

            Length pixelSizeX = metadata.getPixelsPhysicalSizeX(0);
            Length pixelSizeY = metadata.getPixelsPhysicalSizeY(0);
            System.out.println("Pixel size: X=" + pixelSizeX + ", Y=" + pixelSizeY);
        }

        // Step 5: Try to use with OperettaManager
        System.out.println("\n=== Step 5: Testing with OperettaManager ===");
        try {
            OperettaManager opm = new OperettaManager.Builder()
                    .reader(reader)
                    .build();

            System.out.println("SUCCESS: OperettaManager created");
            System.out.println("Plate name: " + opm.getPlateName());

            List<Well> wells = opm.getWells();
            System.out.println("Wells found: " + wells.size());

            if (!wells.isEmpty()) {
                Well firstWell = wells.get(0);
                int row = firstWell.getRow().getValue() + 1;
                int col = firstWell.getColumn().getValue() + 1;
                System.out.println("First well: R" + row + "-C" + col);

                List<Integer> fieldIds = opm.getFieldIds();
                System.out.println("Field IDs: " + fieldIds);
            }

            System.out.println("\n=== SUCCESS: Companion file is compatible with OperettaManager ===");

        } catch (Exception e) {
            System.err.println("FAILED: Could not use companion file with OperettaManager");
            e.printStackTrace();
        }

        // Step 6: Try to read actual pixel data
        System.out.println("\n=== Step 6: Testing pixel data reading ===");
        try {
            reader.setSeries(0);
            int planeSize = reader.getSizeX() * reader.getSizeY() *
                    (reader.getBitsPerPixel() / 8);
            System.out.println("Attempting to read first plane (" + planeSize + " bytes)...");

            byte[] plane = reader.openBytes(0);
            System.out.println("SUCCESS: Read " + plane.length + " bytes");

            // Check if data is non-zero
            boolean hasData = false;
            for (int i = 0; i < Math.min(1000, plane.length); i++) {
                if (plane[i] != 0) {
                    hasData = true;
                    break;
                }
            }
            System.out.println("Data appears " + (hasData ? "valid (non-zero values found)" : "empty (all zeros)"));

        } catch (Exception e) {
            System.err.println("FAILED: Could not read pixel data");
            e.printStackTrace();
        }

        reader.close();
    }
}
